// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(WalletOneContext))]
    [Migration("20201030082054_Fix Task and User")]
    partial class FixTaskandUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessLayer.Model.TaskUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaskUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 740, DateTimeKind.Local).AddTicks(9822),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 740, DateTimeKind.Local).AddTicks(9822),
                            Description = "test1",
                            DirectorId = 1,
                            Name = "test1",
                            PerformerId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4086),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4086),
                            Description = "test2",
                            DirectorId = 1,
                            Name = "test2",
                            PerformerId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4319),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4319),
                            Description = "test3",
                            DirectorId = 1,
                            Name = "test3",
                            PerformerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4327),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4327),
                            Description = "test4",
                            DirectorId = 1,
                            Name = "test4",
                            PerformerId = 5,
                            Status = 4
                        },
                        new
                        {
                            Id = 5,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4331),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4331),
                            Description = "test5",
                            DirectorId = 2,
                            Name = "test5",
                            PerformerId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4347),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4347),
                            Description = "test6",
                            DirectorId = 1,
                            Name = "test6",
                            PerformerId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4351),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4351),
                            Description = "test7",
                            DirectorId = 1,
                            Name = "test7",
                            PerformerId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4355),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4355),
                            Description = "test8",
                            DirectorId = 4,
                            Name = "test8",
                            PerformerId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4359),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4359),
                            Description = "test9",
                            DirectorId = 1,
                            Name = "test9",
                            PerformerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4367),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4367),
                            Description = "test10",
                            DirectorId = 2,
                            Name = "test10",
                            PerformerId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4371),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4371),
                            Description = "test11",
                            DirectorId = 4,
                            Name = "test11",
                            PerformerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4374),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4374),
                            Description = "test12",
                            DirectorId = 5,
                            Name = "test12",
                            PerformerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4374),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4374),
                            Description = "test13",
                            DirectorId = 1,
                            Name = "test13",
                            PerformerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4378),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4378),
                            Description = "test14",
                            DirectorId = 2,
                            Name = "test14",
                            PerformerId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4382),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4382),
                            Description = "test15",
                            DirectorId = 3,
                            Name = "test15",
                            PerformerId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4386),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4386),
                            Description = "test16",
                            DirectorId = 3,
                            Name = "test16",
                            PerformerId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4390),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4390),
                            Description = "test17",
                            DirectorId = 3,
                            Name = "test17",
                            PerformerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4394),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4394),
                            Description = "test18",
                            DirectorId = 3,
                            Name = "test18",
                            PerformerId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4398),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4398),
                            Description = "test19",
                            DirectorId = 4,
                            Name = "test19",
                            PerformerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4402),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4402),
                            Description = "test20",
                            DirectorId = 5,
                            Name = "test20",
                            PerformerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4406),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4406),
                            Description = "test21",
                            DirectorId = 5,
                            Name = "test21",
                            PerformerId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4410),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4410),
                            Description = "test22",
                            DirectorId = 5,
                            Name = "test22",
                            PerformerId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4414),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4414),
                            Description = "test23",
                            DirectorId = 5,
                            Name = "test23",
                            PerformerId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4418),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 744, DateTimeKind.Local).AddTicks(4418),
                            Description = "test24",
                            DirectorId = 1,
                            Name = "test24",
                            PerformerId = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("BusinessLayer.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 747, DateTimeKind.Local).AddTicks(7469),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 747, DateTimeKind.Local).AddTicks(7473),
                            FirstName = "test1",
                            MiddleName = "test1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 748, DateTimeKind.Local).AddTicks(1448),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 748, DateTimeKind.Local).AddTicks(1456),
                            FirstName = "test2",
                            MiddleName = "test2",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 748, DateTimeKind.Local).AddTicks(1547),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 748, DateTimeKind.Local).AddTicks(1547),
                            FirstName = "test3",
                            MiddleName = "test3",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 748, DateTimeKind.Local).AddTicks(1551),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 748, DateTimeKind.Local).AddTicks(1555),
                            FirstName = "test4",
                            MiddleName = "test4",
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            DateCreate = new DateTime(2020, 10, 30, 13, 20, 53, 748, DateTimeKind.Local).AddTicks(1559),
                            DateLastEdit = new DateTime(2020, 10, 30, 13, 20, 53, 748, DateTimeKind.Local).AddTicks(1559),
                            FirstName = "test5",
                            MiddleName = "test5",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
